language: python

install:
  - pip3 install git+https://github.com/Madders/video.git
  - pip3 install -U Sphinx==2.4.4
  - pip3 install --upgrade recommonmark
  - pip3 install sphinx_rtd_theme

script:
  - cd docs
  #- make html
  - if [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ];
    then make html;
  - if [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_PULL_REQUEST" != "false" ];
    then make html;
